// Packages the game's named ES imports/exports as a classic script for file://.
// No runtime loader or third-party build dependencies are needed.
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Script } from 'node:vm';

const root = new URL('../', import.meta.url);
const generated = 'Generated by node scripts/build.mjs. Edit the source files, not this file.';

export async function buildAssets() {
  const modules = new Map(), visiting = new Set(), chunks = [];

  async function visit(url) {
    if (visiting.has(url.href)) throw new Error(`Circular module dependency: ${url}`);
    if (modules.has(url.href)) return modules.get(url.href);
    if (!url.href.startsWith(root.href)) throw new Error(`Module outside the game directory: ${url}`);
    visiting.add(url.href);
    let source = (await readFile(url, 'utf8')).replace(/\r\n/g, '\n');
    const imports = [...source.matchAll(/^import\s+\{([^}]+)\}\s+from\s+(['"])(\.\.?\/[^'"\n]+)\2;[ \t]*$/gm)];
    for (const match of imports) {
      const dependency = await visit(new URL(match[3], url));
      const bindings = match[1].split(',').map(value => value.trim()).filter(Boolean).map(value => {
        const binding = /^([\w$]+)(?:\s+as\s+([\w$]+))?$/.exec(value);
        if (!binding || !dependency.exports.includes(binding[1])) throw new Error(`Unsupported import '${value}' in ${url}`);
        return binding[2] ? `${binding[1]}: ${binding[2]}` : binding[1];
      });
      source = source.replace(match[0], `const { ${bindings.join(', ')} } = ${dependency.id};`);
    }
    const names = [];
    source = source.replace(/^export (const|function|class) ([\w$]+)/gm, (_, kind, name) => {
      names.push(name);
      return `${kind} ${name}`;
    });
    const module = { id: `__module${modules.size}`, exports: names };
    const chunk = `// ${url.href.slice(root.href.length)}\nconst ${module.id} = (() => {\n${source.trimEnd()}\nreturn { ${names.join(', ')} };\n})();`;
    // Remaining module syntax fails here instead of producing a broken release.
    new Script(`'use strict';\n${chunk}`, { filename: url.pathname });
    modules.set(url.href, module);
    visiting.delete(url.href);
    chunks.push(chunk);
    return module;
  }

  await visit(new URL('structure-worker.mjs', root));
  const worker = `(() => {\n'use strict';\n${chunks.join('\n\n')}\n})();`;
  new Script(worker, { filename: 'structure-worker' });
  modules.clear(); visiting.clear(); chunks.length = 0;
  await visit(new URL('game.js', root));
  const script = `/* ${generated} */\n(() => {\n'use strict';\nglobalThis.incrementalisWorkerSource = ${JSON.stringify(worker)};\n${chunks.join('\n\n')}\n})();\n`;
  new Script(script, { filename: 'game.bundle.js' });

  // Browsers can also restrict file:// font requests. Data URLs keep them local
  // and avoid font CORS requests while preserving subsets and OFL licenses.
  const fontSource = new URL('assets/fonts/fonts.css', root);
  let fonts = (await readFile(fontSource, 'utf8')).replace(/\r\n/g, '\n');
  for (const match of [...fonts.matchAll(/url\('([^']+\.woff2)'\)/g)]) {
    const data = await readFile(new URL(match[1], fontSource));
    if (data.toString('ascii', 0, 4) !== 'wOF2' || data.readUInt32BE(8) !== data.length) throw new Error(`Invalid font: ${match[1]}`);
    fonts = fonts.replace(match[0], `url('data:font/woff2;base64,${data.toString('base64')}')`);
  }
  return new Map([
    ['game.bundle.js', script],
    ['assets/fonts/fonts.bundle.css', `/* ${generated} */\n${fonts}`],
  ]);
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  for (const [name, content] of await buildAssets()) {
    await writeFile(new URL(name, root), content);
    console.info(`${name}: ${Buffer.byteLength(content)} bytes`);
  }
}
